vim.keymap.set("n", "<leader>ste", function()
    vim.cmd.vnew()
    vim.cmd.term()
    vim.cmd.wincmd("J")
    vim.api.nvim_win_set_height(0, 15)
    vim.fn.chansend(vim.bo.channel, { "stack test\r\n" })
end)

vim.keymap.set("n", "<leader>stg", function()
    vim.cmd.vnew()
    vim.cmd.term()
    vim.cmd.wincmd("J")
    vim.api.nvim_win_set_height(0, 15)
    vim.fn.chansend(vim.bo.channel, { "stack ghci\r\n" })
end)
